fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    eyplib: "git://github.com/NTTCom-MS/eyp-eyplib.git"
    systemd: "git://github.com/NTTCom-MS/eyp-systemd.git"
  symlinks:
    redis: "#{source_dir}"
